# AUTO-GENERATED by DialogueApp — No editar manualmente
# Valores iniciales de variables narrativas del proyecto
class_name NarrativeDefaults

const DEFAULTS: Dictionary = {
	"estado": false,
	"respondio": false,
}
