// @ts-check
const express = require('express');
const path = require('path');
const fs = require('fs');

const app = express();
const PORT = process.env.PORT || 3131;

// Path constants
const BASE_SRC = path.resolve(__dirname, '../rpg-g/src');
const RPG_ROOT = path.resolve(__dirname, '../rpg-g');
const CONFIG_FILE = path.resolve(__dirname, 'data/project_config.json');
const LAYOUTS_DIR = path.resolve(__dirname, 'data/layouts');
const PUBLIC_DIR = path.resolve(__dirname, 'public');
// Solo lectura: catalogo de items / estados (nunca se escribe fuera de rpg-g/src)
const DATA_DIR = path.resolve(__dirname, '../rpg-g/data');
const VAR_NAME_RE = /^[a-z][a-z0-9_]*$/;
const ALLOWED_VAR_TYPES = ['bool', 'int', 'float', 'string'];

/**
 * Normaliza la config: una sola lista `variables` (elimina `flags`),
 * descarta variables con nombre invalido o duplicado.
 * @param {any} raw
 * @returns {any}
 */
function normalizeConfig(raw) {
  const cfg = (raw && typeof raw === 'object') ? { ...raw } : {};
  const source = Array.isArray(cfg.variables) ? cfg.variables : (Array.isArray(cfg.flags) ? cfg.flags : []);
  delete cfg.flags;
  const seen = new Set();
  cfg.variables = [];
  for (const v of source) {
    const name = v && typeof v.name === 'string' ? v.name : '';
    if (!VAR_NAME_RE.test(name)) {
      console.warn(`[config] Variable descartada (nombre invalido, debe cumplir ${VAR_NAME_RE}): ${JSON.stringify(v && v.name)}`);
      continue;
    }
    if (seen.has(name)) {
      console.warn(`[config] Variable duplicada descartada: "${name}"`);
      continue;
    }
    seen.add(name);
    cfg.variables.push(v);
  }
  return cfg;
}

/**
 * Lee (solo lectura) los .tres de un subdirectorio de rpg-g/data y extrae id/name.
 * @param {string} subdir
 * @returns {Promise<{id: string, name: string}[]>}
 */
async function readResourceIds(subdir) {
  const dir = path.resolve(DATA_DIR, subdir);
  if (!dir.startsWith(DATA_DIR + path.sep)) return [];
  const files = await scanDir(dir, '.tres');
  /** @type {{id: string, name: string}[]} */
  const out = [];
  for (const f of files.sort()) {
    try {
      const content = await fs.promises.readFile(f, 'utf-8');
      const idm = content.match(/^id\s*=\s*"([^"]+)"/m);
      if (!idm) continue;
      const nm = content.match(/^name\s*=\s*"([^"]*)"/m);
      out.push({ id: idm[1], name: nm ? nm[1] : '' });
    } catch (err) {
      console.error(`[readResourceIds] ${f}:`, err);
    }
  }
  return out;
}

/**
 * Validates that a target path is safely contained within BASE_SRC.
 * @param {string} targetPath - Absolute path to validate.
 * @returns {boolean} True if safely inside BASE_SRC, false otherwise.
 */
function isSafePath(targetPath) {
  const normalizedTarget = path.normalize(targetPath);
  const normalizedBase = path.normalize(BASE_SRC);
  return normalizedTarget === normalizedBase || normalizedTarget.startsWith(normalizedBase + path.sep);
}

/**
 * Comprueba que la ruta sea un archivo .dialogue.
 * @param {string} targetPath
 * @returns {boolean}
 */
function isDialogueFile(targetPath) {
  return targetPath.toLowerCase().endsWith('.dialogue');
}

/**
 * Escritura atómica: escribe a un temporal en el mismo directorio y renombra.
 * @param {string} filePath
 * @param {string} data
 * @returns {Promise<void>}
 */
async function writeFileAtomic(filePath, data) {
  const tmp = `${filePath}.${process.pid}.${Date.now()}.tmp`;
  try {
    await fs.promises.writeFile(tmp, data, 'utf-8');
    await fs.promises.rename(tmp, filePath);
  } catch (err) {
    await fs.promises.unlink(tmp).catch(() => {});
    throw err;
  }
}

/**
 * Genera el contenido de narrative_defaults.gd a partir de las variables.
 * @param {{name: string, type?: string, defaultValue?: any}[]} variables
 * @returns {string}
 */
function buildNarrativeDefaults(variables) {
  let gd = '# AUTO-GENERATED by DialogueApp — No editar manualmente\n';
  gd += '# Valores iniciales de variables narrativas del proyecto\n';
  gd += 'class_name NarrativeDefaults\n\n';
  gd += 'const DEFAULTS: Dictionary = {\n';
  for (const v of variables) {
    const type = ALLOWED_VAR_TYPES.includes(v.type) ? v.type : 'bool';
    const raw = v.defaultValue;
    let val;
    if (type === 'bool') {
      val = (raw === true || raw === 'true') ? 'true' : 'false';
    } else if (type === 'int') {
      val = String(parseInt(raw, 10) || 0);
    } else if (type === 'float') {
      const f = parseFloat(raw);
      val = Number.isFinite(f) ? (Number.isInteger(f) ? f.toFixed(1) : String(f)) : '0.0';
    } else {
      val = JSON.stringify(raw === undefined || raw === null ? '' : String(raw));
    }
    gd += `\t${JSON.stringify(v.name)}: ${val},\n`;
  }
  gd += '}\n';
  return gd;
}

/**
 * Recursively scans directory for files with a given extension (excluding .import files).
 * @param {string} dir - Directory to search.
 * @param {string} ext - Extension to match (e.g. '.dialogue' or '.tscn').
 * @returns {Promise<string[]>} List of absolute file paths.
 */
async function scanDir(dir, ext) {
  /** @type {string[]} */
  const results = [];
  try {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        const subFiles = await scanDir(fullPath, ext);
        results.push(...subFiles);
      } else if (entry.isFile()) {
        if (fullPath.endsWith(ext) && !fullPath.endsWith(`${ext}.import`)) {
          results.push(fullPath);
        }
      }
    }
  } catch (err) {
    console.error(`[scanDir] Failed to scan directory "${dir}":`, err);
  }
  return results;
}

/**
 * @typedef {Object} TriggerInfo
 * @property {string} name - Trigger name.
 * @property {string} source - Source type ('tscn').
 * @property {string} file - Relative path from rpg-g root.
 */

/**
 * Parses a .tscn file content and extracts trigger entries.
 * @param {string} content - Raw content of the .tscn file.
 * @param {string} relPath - Relative path from rpg-g root.
 * @returns {TriggerInfo[]} Extracted triggers.
 */
function extractTriggersFromTscn(content, relPath) {
  if (!content.includes('game_trigger.gd')) {
    return [];
  }

  /** @type {TriggerInfo[]} */
  const triggers = [];
  const lines = content.split(/\r?\n/);

  // 1. Collect all ExtResource IDs referencing game_trigger.gd
  /** @type {Set<string>} */
  const triggerExtIds = new Set();
  for (const line of lines) {
    if (line.includes('game_trigger.gd')) {
      const idMatch = line.match(/\bid="?([^"\s\]]+)"?/);
      if (idMatch) {
        triggerExtIds.add(idMatch[1]);
      }
    }
  }

  // 2. Identify the root node name (first line matching [node name=...)
  let rootNodeName = null;
  for (const line of lines) {
    const rootMatch = line.match(/\[node\s+[^\]]*\bname\s*=\s*"([^"]+)"/);
    if (rootMatch) {
      rootNodeName = rootMatch[1];
      break;
    }
  }

  if (rootNodeName) {
    triggers.push({
      name: rootNodeName,
      source: 'tscn',
      file: relPath
    });
  }

  // 3. Identify individual nodes attached to game_trigger.gd
  let currentSectionType = null;
  let currentNodeName = null;
  let currentHasTrigger = false;

  for (const line of lines) {
    if (line.startsWith('[')) {
      if (currentSectionType === 'node' && currentNodeName && currentHasTrigger) {
        triggers.push({
          name: currentNodeName,
          source: 'tscn',
          file: relPath
        });
      }

      const nodeMatch = line.match(/^\[node\s+[^\]]*\bname\s*=\s*"([^"]+)"/);
      if (nodeMatch) {
        currentSectionType = 'node';
        currentNodeName = nodeMatch[1];
        currentHasTrigger = line.includes('game_trigger.gd');
      } else {
        currentSectionType = 'other';
        currentNodeName = null;
        currentHasTrigger = false;
      }
    } else if (currentSectionType === 'node') {
      if (line.includes('game_trigger.gd')) {
        currentHasTrigger = true;
      } else {
        for (const extId of triggerExtIds) {
          if (line.includes(`ExtResource("${extId}")`) || line.includes(`ExtResource(${extId})`)) {
            currentHasTrigger = true;
            break;
          }
        }
      }
    }
  }

  if (currentSectionType === 'node' && currentNodeName && currentHasTrigger) {
    triggers.push({
      name: currentNodeName,
      source: 'tscn',
      file: relPath
    });
  }

  return triggers;
}

// 1. Static files middleware
app.use(express.static(PUBLIC_DIR));

// 2. JSON body parser (sin CORS: la app se sirve desde el mismo origen)
app.use(express.json({ limit: '5mb' }));

app.get('/favicon.ico', (req, res) => res.status(204).end());

// 3. API Endpoints

/**
 * GET /api/dialogues
 * Scans BASE_SRC for *.dialogue files.
 */
app.get('/api/dialogues', async (req, res) => {
  try {
    const files = await scanDir(BASE_SRC, '.dialogue');
    const result = files.map((absPath) => ({
      name: path.basename(absPath),
      path: absPath,
      relPath: path.relative(RPG_ROOT, absPath).replace(/\\/g, '/')
    }));
    res.json(result);
  } catch (err) {
    console.error('[GET /api/dialogues] Error:', err);
    res.status(500).json({ error: 'Failed to scan dialogues' });
  }
});

/**
 * GET /api/dialogues/read?path=<relPath>
 * Reads dialogue file content.
 */
app.get('/api/dialogues/read', async (req, res) => {
  try {
    const relPath = req.query.path;
    if (!relPath || typeof relPath !== 'string') {
      return res.status(400).json({ error: 'Missing or invalid "path" query parameter' });
    }

    const targetPath = path.resolve(RPG_ROOT, relPath);
    if (!isSafePath(targetPath)) {
      return res.status(403).json({ error: 'Forbidden: Path must be inside rpg-g/src' });
    }
    if (!isDialogueFile(targetPath)) {
      return res.status(400).json({ error: 'Solo se permiten archivos .dialogue' });
    }

    try {
      const content = await fs.promises.readFile(targetPath, 'utf-8');
      res.json({ content });
    } catch (readErr) {
      if (/** @type {NodeJS.ErrnoException} */ (readErr).code === 'ENOENT') {
        res.json({ content: '' });
      } else {
        throw readErr;
      }
    }
  } catch (err) {
    console.error('[GET /api/dialogues/read] Error:', err);
    res.status(500).json({ error: 'Failed to read dialogue file' });
  }
});

/**
 * POST /api/dialogues/save
 * Saves content to dialogue file.
 */
app.post('/api/dialogues/save', async (req, res) => {
  try {
    const { path: relPath, content } = req.body || {};
    if (!relPath || typeof relPath !== 'string') {
      return res.status(400).json({ error: 'Missing or invalid "path" in body' });
    }

    const targetPath = path.resolve(RPG_ROOT, relPath);
    if (!isSafePath(targetPath)) {
      return res.status(403).json({ error: 'Forbidden: Path must be inside rpg-g/src' });
    }

    if (!isDialogueFile(targetPath)) {
      return res.status(400).json({ error: 'Solo se permiten archivos .dialogue' });
    }
    if (content !== undefined && typeof content !== 'string') {
      return res.status(400).json({ error: 'Invalid "content" in body' });
    }

    await fs.promises.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.promises.writeFile(targetPath, content ?? '', 'utf-8');
    res.json({ ok: true });
  } catch (err) {
    console.error('[POST /api/dialogues/save] Error:', err);
    res.status(500).json({ error: 'Failed to save dialogue file' });
  }
});

/**
 * POST /api/dialogues/create
 * Creates a new dialogue file with starter content if it doesn't already exist.
 */
app.post('/api/dialogues/create', async (req, res) => {
  try {
    const { relPath } = req.body || {};
    if (!relPath || typeof relPath !== 'string') {
      return res.status(400).json({ error: 'Missing or invalid "relPath" in body' });
    }

    const targetPath = path.resolve(RPG_ROOT, relPath);
    if (!isSafePath(targetPath)) {
      return res.status(403).json({ error: 'Forbidden: Path must be inside rpg-g/src' });
    }

    if (!isDialogueFile(targetPath)) {
      return res.status(400).json({ error: 'Solo se permiten archivos .dialogue' });
    }

    try {
      await fs.promises.access(targetPath);
      return res.json({ ok: false, error: 'already_exists' });
    } catch {
      // File does not exist, can be created
    }

    await fs.promises.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.promises.writeFile(targetPath, '~ start\n\n=> END\n', 'utf-8');
    res.json({ ok: true, path: relPath });
  } catch (err) {
    console.error('[POST /api/dialogues/create] Error:', err);
    res.status(500).json({ error: 'Failed to create dialogue file' });
  }
});

/**
 * GET /api/config
 * Reads project configuration file or creates default if not found.
 */
app.get('/api/config', async (req, res) => {
  try {
    let data;
    try {
      data = await fs.promises.readFile(CONFIG_FILE, 'utf-8');
    } catch (readErr) {
      if (/** @type {NodeJS.ErrnoException} */ (readErr).code !== 'ENOENT') throw readErr;
      // Solo si el archivo no existe se crea el default
      const initialConfig = { actors: [], variables: [], triggers: [] };
      await fs.promises.mkdir(path.dirname(CONFIG_FILE), { recursive: true });
      await writeFileAtomic(CONFIG_FILE, JSON.stringify(initialConfig, null, 2));
      return res.json(initialConfig);
    }
    // JSON invalido -> 500 sin sobrescribir el archivo
    let parsed;
    try {
      parsed = JSON.parse(data);
    } catch (parseErr) {
      console.error('[GET /api/config] project_config.json no es JSON valido (no se modifica):', parseErr);
      return res.status(500).json({ error: 'project_config.json no es JSON valido' });
    }
    return res.json(normalizeConfig(parsed));
  } catch (err) {
    console.error('[GET /api/config] Error:', err);
    res.status(500).json({ error: 'Failed to get config' });
  }
});

/**
 * POST /api/config
 * Saves project configuration.
 */
app.post('/api/config', async (req, res) => {
  try {
    if (!req.body || typeof req.body !== 'object') {
      return res.status(400).json({ error: 'Invalid config body' });
    }
    const configData = normalizeConfig(req.body);

    await fs.promises.mkdir(path.dirname(CONFIG_FILE), { recursive: true });
    await writeFileAtomic(CONFIG_FILE, JSON.stringify(configData, null, 2));

    // Auto-generate narrative_defaults.gd
    const defaultsPath = path.resolve(BASE_SRC, 'core/data/narrative_defaults.gd');
    await fs.promises.mkdir(path.dirname(defaultsPath), { recursive: true });
    await writeFileAtomic(defaultsPath, buildNarrativeDefaults(configData.variables));

    res.json({ ok: true });
  } catch (err) {
    console.error('[POST /api/config] Error:', err);
    res.status(500).json({ error: 'Failed to save config' });
  }
});

/**
 * GET /api/system-variables
 * Variables de solo lectura del juego: player.*, item.<id>, status.<id>.
 */
app.get('/api/system-variables', async (req, res) => {
  try {
    /** @type {{path: string, type: string, readonly: boolean, description: string}[]} */
    const list = [
      { path: 'player.health', type: 'int', readonly: true, description: 'Vida actual del jugador' },
      { path: 'player.max_health', type: 'int', readonly: true, description: 'Vida maxima del jugador' },
      { path: 'player.gold', type: 'int', readonly: true, description: 'Oro del jugador' },
      { path: 'player.speed', type: 'float', readonly: true, description: 'Velocidad del jugador' },
      { path: 'player.strength', type: 'int', readonly: true, description: 'Fuerza del jugador' },
      { path: 'player.resistance', type: 'int', readonly: true, description: 'Resistencia del jugador' },
    ];
    for (const it of await readResourceIds('items')) {
      list.push({ path: `item.${it.id}`, type: 'int', readonly: true, description: `Cantidad en inventario${it.name ? ': ' + it.name : ''}` });
    }
    for (const st of await readResourceIds('status_effects')) {
      list.push({ path: `status.${st.id}`, type: 'bool', readonly: true, description: `Estado activo${st.name ? ': ' + st.name : ''}` });
    }
    res.json(list);
  } catch (err) {
    console.error('[GET /api/system-variables] Error:', err);
    res.status(500).json({ error: 'Failed to read system variables' });
  }
});

/**
 * GET /api/triggers
 * Scans BASE_SRC for .tscn files using game_trigger.gd.
 */
app.get('/api/triggers', async (req, res) => {
  try {
    const tscnFiles = await scanDir(BASE_SRC, '.tscn');
    /** @type {TriggerInfo[]} */
    const allTriggers = [];

    for (const filePath of tscnFiles) {
      try {
        const content = await fs.promises.readFile(filePath, 'utf-8');
        const relPath = path.relative(RPG_ROOT, filePath).replace(/\\/g, '/');
        const fileTriggers = extractTriggersFromTscn(content, relPath);
        allTriggers.push(...fileTriggers);
      } catch (fileErr) {
        console.error(`[GET /api/triggers] Error reading ${filePath}:`, fileErr);
      }
    }

    // Deduplicate by trigger name
    /** @type {Set<string>} */
    const seen = new Set();
    /** @type {TriggerInfo[]} */
    const uniqueTriggers = [];

    for (const item of allTriggers) {
      if (!seen.has(item.name)) {
        seen.add(item.name);
        uniqueTriggers.push(item);
      }
    }

    res.json(uniqueTriggers);
  } catch (err) {
    console.error('[GET /api/triggers] Error:', err);
    res.status(500).json({ error: 'Failed to scan triggers' });
  }
});

/**
 * GET /api/layouts/:layoutId
 * Gets layout data for a specific dialogue.
 */
app.get('/api/layouts/:layoutId', async (req, res) => {
  try {
    const layoutId = path.basename(req.params.layoutId);
    const layoutPath = path.join(LAYOUTS_DIR, `${layoutId}.json`);

    try {
      const data = await fs.promises.readFile(layoutPath, 'utf-8');
      res.json(JSON.parse(data));
    } catch (readErr) {
      if (/** @type {NodeJS.ErrnoException} */ (readErr).code === 'ENOENT') {
        res.json({ nodes: {} });
      } else {
        throw readErr;
      }
    }
  } catch (err) {
    console.error('[GET /api/layouts/:layoutId] Error:', err);
    res.status(500).json({ error: 'Failed to read layout' });
  }
});

/**
 * POST /api/layouts/:layoutId
 * Saves layout data for a specific dialogue.
 */
app.post('/api/layouts/:layoutId', async (req, res) => {
  try {
    const layoutId = path.basename(req.params.layoutId);
    const layoutPath = path.join(LAYOUTS_DIR, `${layoutId}.json`);

    await fs.promises.mkdir(LAYOUTS_DIR, { recursive: true });
    await fs.promises.writeFile(layoutPath, JSON.stringify(req.body || {}, null, 2), 'utf-8');
    res.json({ ok: true });
  } catch (err) {
    console.error('[POST /api/layouts/:layoutId] Error:', err);
    res.status(500).json({ error: 'Failed to save layout' });
  }
});

/**
 * GET /api/browse?dir=<relPath>
 * Lists directories inside rpg-g/src/ for folder browsing.
 * Returns { directories: string[], currentPath: string }
 */
app.get('/api/browse', async (req, res) => {
  try {
    const relDir = req.query.dir || 'src';
    const targetPath = path.resolve(RPG_ROOT, relDir);
    if (!isSafePath(targetPath)) {
      return res.status(403).json({ error: 'Forbidden: Path must be inside rpg-g/src' });
    }

    const entries = await fs.promises.readdir(targetPath, { withFileTypes: true });
    const directories = entries
      .filter(e => e.isDirectory())
      .map(e => e.name)
      .sort();

    res.json({
      currentPath: path.relative(RPG_ROOT, targetPath).replace(/\\/g, '/'),
      directories,
    });
  } catch (err) {
    console.error('[GET /api/browse] Error:', err);
    res.status(500).json({ error: 'Failed to browse directory' });
  }
});

// 4. Start server (solo al ejecutar `node server.js`; al hacer require() no se escucha)
/** @type {import('http').Server | null} */
let server = null;
if (require.main === module) {
  server = app.listen(PORT, '127.0.0.1', () => {
    console.log(`DialogueApp server running at http://127.0.0.1:${PORT}`);
  });
}

module.exports = { normalizeConfig, app, server, scanDir, extractTriggersFromTscn, isSafePath, buildNarrativeDefaults, writeFileAtomic };
